name: Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'

      - name: Install Dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install cypress

      - name: Build
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Run Cypress Tests
        run: npm run cypress:run
