name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
# Set environment variable

  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
       
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Cypress run 
       uses: cypress-io/github-action@v2
       with:
         build: npm run build
         start: npm start
   # Install dependencies and run tests for the client application
     - name: Install and Test Client

       run: |
          npm install
          npm run test

      # Install dependencies, export environment variables to be used by application and run tests for the server application
     - name: Install and Test Server
       working-directory: ./backend
       run: |
          npm install
          
          npm run test
     - run: npm ci
     - run: npm run build --if-present
     - run: npm run lint:check & npm test
